# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.ssh.insert_key = false

  config.vm.define :dc01 do |dc01|
    dc01.vm.box = "windows2022core"
    dc01.vm.guest = "windows"
    dc01.vm.synced_folder '.', '/vagrant', disabled: true
    dc01.winssh.shell = "powershell"
    dc01.ssh.shell = "powershell"
    dc01.vm.hostname = "dc01"
    #dc01.vm.provision "shell", inline: "install-windowsfeature AD-Domain-Services", powershell_elevated_interactive: true
    #dc01.vm.provision "shell", inline: "install-addsforest -force -domainname domain.test -installdns -safemodeadministratorpassword (convertto-securestring 'NotSecure1@' -asplaintext -force)"
  end

  config.vm.define :dc02 do |dc02|
    dc02.vm.box = "windows2022core"
    dc02.vm.guest = "windows"
    dc02.vm.synced_folder '.', '/vagrant', disabled: true
    dc02.winssh.shell = "powershell"
    dc02.ssh.shell = "powershell"
    dc02.vm.hostname = "dc02"
    #dc02.vm.provision "shell", inline: "install-windowsfeature AD-Domain-Services"
  end

  config.vm.define :win03 do |win03|
    win03.vm.box = "windows2022desktop"
    win03.vm.guest = "windows"
    win03.vm.synced_folder '.', '/vagrant', disabled: true
    win03.winssh.shell = "powershell"
    win03.ssh.shell = "powershell"
    win03.vm.hostname = "win03"
  end
  
  config.vm.define :lin04 do |lin04|
    lin04.vm.box = "ubuntu2204"
    lin04.vm.synced_folder '.', '/vagrant', disabled: true
    lin04.vm.hostname = "lin04"
    lin04.vm.provision "file", source: "id_rsa", destination: ".ssh/id_rsa"
    lin04.vm.provision "file", source: "hosts", destination: "hosts"
    lin04.vm.provision "file", source: "lab01.yml", destination: "lab01.yml"
    lin04.vm.provision "shell", inline: "cp .ssh/id_rsa /root/.ssh/id_rsa"
    lin04.vm.provision "shell", inline: "chmod go-rw .ssh/id_rsa"
    lin04.vm.provision "shell", inline: "chmod go-rw /root/.ssh/id_rsa"
    lin04.vm.provision "shell", inline: "rm -f .ssh/known_hosts"
    lin04.vm.provision "shell", inline: "ssh-keyscan dc01 | grep rsa >> .ssh/known_hosts"
    lin04.vm.provision "shell", inline: "ssh-keyscan dc02 | grep rsa >> .ssh/known_hosts"
    lin04.vm.provision "shell", inline: "ssh-keyscan win03 | grep rsa >> .ssh/known_hosts"
    lin04.vm.provision "shell", inline: "cp .ssh/known_hosts /root/.ssh/known_hosts"
    lin04.vm.provision "shell", inline: "ansible-playbook lab01.yml -i hosts -u vagrant"
  end
end
